# fly.toml app configuration file generated for bolao-copa-microservice on 2026-06-09T14:08:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bolao-copa-microservice'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1  # Mantém 1 máquina sempre up para APScheduler sobreviver ao auto-stop

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
