export const TIME_CODIGOS: Record<string, string> = {
  'Argentina': 'ar',
  'Alemanha': 'de',
  'Argélia': 'dz',
  'Áustria': 'at',
  'África do Sul': 'za',
  'Austrália': 'au',
  'Bélgica': 'be',
  'Bósnia': 'ba',
  'Brasil': 'br',
  'Canadá': 'ca',
  'Cabo Verde': 'cv',
  'Catar': 'qa',
  'Colômbia': 'co',
  'Congo': 'cd',
  'Coreia do Sul': 'kr',
  'Costa do Marfim': 'ci',
  'Croácia': 'hr',
  'Curaçao': 'cw',
  'Dinamarca': 'dk',
  'Egito': 'eg',
  'Equador': 'ec',
  'Escócia': 'gb-sct',
  'Espanha': 'es',
  'EUA': 'us',
  'França': 'fr',
  'Gana': 'gh',
  'Haiti': 'ht',
  'Holanda': 'nl',
  'Inglaterra': 'gb-eng',
  'Irã': 'ir',
  'Iraque': 'iq',
  'Japão': 'jp',
  'Jordânia': 'jo',
  'Marrocos': 'ma',
  'México': 'mx',
  'Noruega': 'no',
  'Nova Zelândia': 'nz',
  'Panamá': 'pa',
  'Paraguai': 'py',
  'Polônia': 'pl',
  'Portugal': 'pt',
  'República Checa': 'cz',
  'Arábia Saudita': 'sa',
  'Senegal': 'sn',
  'Suécia': 'se',
  'Suíça': 'ch',
  'Tunísia': 'tn',
  'Turquia': 'tr',
  'Uruguai': 'uy',
  'Uzbequistão': 'uz',
}

export function getTimeFlag(nome: string): string | null {
  return TIME_CODIGOS[nome] ?? null
}
